name: Scrape latest data

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Fetch latest data
      run: |-
        curl "https://api.resultados.eleccionesgenerales2021.pe/results/10/000000?name=param" | jq . > elecciones_generales_2021.json
    - name: Commit/Push if data changed
      run: |-
        git config user.name "Automatizado"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Últimos datos: ${timestamp}" || exit 0
        git push
    - name: Setup Dart SDK
      uses: dart-lang/setup-dart@v1.0
    - name: Processing
      run: |-
        dart --version
        dart procesador.dart
